report_generator_agent = dict(
    workdir="workdir/code_review/report_generator",
    name="report_generator",
    type="ToolCallingAgent",
    description="Report generation specialist that synthesizes all review results into comprehensive Markdown reports",
    model_name="openrouter/gemini-2.0-flash-exp:free",
    prompt_name="report_generator",
    memory_name="general_memory_system",
    max_tools=5,
    max_steps=10,
    review_steps=3,
    log_max_length=1000,
    use_todo=False,
    require_grad=False,
)
