security_review_agent = dict(
    workdir="workdir/code_review/security_review",
    name="security_review",
    type="ToolCallingAgent",
    description="Security review specialist analyzing vulnerabilities, injection risks, hardcoded secrets, and security best practices",
    model_name="openrouter/gemini-2.0-flash-exp:free",
    prompt_name="security_review",
    memory_name="general_memory_system",
    max_tools=10,
    max_steps=20,
    review_steps=5,
    log_max_length=1000,
    use_todo=False,
    require_grad=True,
)
